jobs:
  build_on_MacOS:
    name: Build on MacOS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11.0.5
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.15
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Build MCinaBox Debug (with gradle)
      run: 'chmod +x gradlew

        ./gradlew clean :app:assembleDebug

        '
      shell: bash
    - continue-on-error: true
      name: Change APK name
      run: 'mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/MCinaBox-${{
        runner.os }}-Debug.apk

        '
      shell: bash
    - continue-on-error: true
      name: Upload All Pack
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-DebugPack
        path: app/build/outputs
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-Debug.apk
        path: app/build/outputs/apk/debug/MCinaBox-${{ runner.os }}-Debug.apk
  build_on_Ubuntu:
    name: Build on Ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11.0.5
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.15
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Build MCinaBox Debug (with gradle)
      run: 'chmod +x gradlew

        ./gradlew clean :app:assembleDebug

        '
      shell: bash
    - continue-on-error: true
      name: Change APK name
      run: 'mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/MCinaBox-${{
        runner.os }}-Debug.apk

        '
      shell: bash
    - continue-on-error: true
      name: Upload All Pack
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-DebugPack
        path: app/build/outputs
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-Debug.apk
        path: app/build/outputs/apk/debug/MCinaBox-${{ runner.os }}-Debug.apk
  build_on_Windows:
    name: Build on Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11.0.5
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.15
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Build MCinaBox Debug (with gradle)
      run: 'chmod +x gradlew

        ./gradlew clean :app:assembleDebug

        '
      shell: bash
    - continue-on-error: true
      name: Change APK name
      run: 'mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/MCinaBox-${{
        runner.os }}-Debug.apk

        '
      shell: bash
    - continue-on-error: true
      name: Upload All Pack
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-DebugPack
        path: app/build/outputs
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-Debug.apk
        path: app/build/outputs/apk/debug/MCinaBox-${{ runner.os }}-Debug.apk
name: APK Debug
on:
  repository_dispatch:
    types: trigger-ga___APK_Debug.yml
